# Generated by Django 3.0.2 on 2020-01-07 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Servant',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('rarity', models.IntegerField(choices=[(5, '★5'), (4, '★4'), (3, '★3'), (2, '★2'), (1, '★1'), (0, '★0')])),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chaldea_database_api.Class')),
            ],
        ),
    ]
