# Generated by Django 3.0.2 on 2020-01-08 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chaldea_database_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servant',
            name='name_en',
            field=models.CharField(default='英語名', max_length=50, verbose_name='英語名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servant',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chaldea_database_api.Class', verbose_name='クラス'),
        ),
        migrations.AlterField(
            model_name='servant',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='servant',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='No.'),
        ),
        migrations.AlterField(
            model_name='servant',
            name='rarity',
            field=models.IntegerField(choices=[(5, '★5'), (4, '★4'), (3, '★3'), (2, '★2'), (1, '★1'), (0, '★0')], verbose_name='レアリティ'),
        ),
    ]
